### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Konfekt** [Coacher/vim-virtualenv#1]
Thank you very much for this plug-in.

Since https://github.com/plytophogy/vim-virtualenv/ is now defunct but had some following, maybe a quick comparison note would be helpful

**Comment by Konfekt** [comment]
By the way, in this [discussion](https://github.com/ubaldot/vim-conda-activate/issues/4) I didn't grasp why the counterpart for conda needed to be inside the environment before, but it just seems that your plug-in solved this more cleanly. Maybe you could give a hint there if this is really necessariy

**Comment by Konfekt** [comment]
For example, I create a virtual environment in the current work dir by `virtualenv .`.
Now I'd like to activate it by `:VirtualEnvActivate` but of course I am always thrown back to missing a config file

```
vim-virtualenv: '/home/nage_en/.virtualenvs' is not a directory
Error detected while processing function virtualenv#activate:
line   36:
E121: Undefined variable: s:state
E116: Invalid arguments for function has_key(s:state, 'virtualenv_directory') && (l
:target ==# s:state['virtualenv_directory'])
```

and then

```
Error detected while processing function virtualenv#activate:
line   36:
E121: Undefined variable: s:state
E116: Invalid arguments for function has_key(s:state, 'virtualenv_directory') && (l
:target ==# s:state['virtualenv_directory'])
```

**Comment by Konfekt** [comment]
For example, I create a virtual environment in the current work dir by `virtualenv .`.
Now I'd like to activate it by `:VirtualEnvActivate` but of course I am always thrown back to missing a central user dir

```
vim-virtualenv: '/home/konfekt/.virtualenvs' is not a directory
Error detected while processing function virtualenv#activate:
line   36:
E121: Undefined variable: s:state
E116: Invalid arguments for function has_key(s:state, 'virtualenv_directory') && (l
:target ==# s:state['virtualenv_directory'])
```

and then

```
Error detected while processing function virtualenv#activate:
line   36:
E121: Undefined variable: s:state
E116: Invalid arguments for function has_key(s:state, 'virtualenv_directory') && (l
:target ==# s:state['virtualenv_directory'])
```

**Comment by Coacher** [comment]
@Konfekt, thank you for the contribution.

I can see at least three points here: request for reference, smth regarding conda and the actual error. Please create separate issues for the latter two.

Let's keep this issue solely about the reference to jmcantrell's plugin.

**Comment by Coacher** [comment]
A while ago this plugin was started as a fork from jmcantrell's plugin.
However, nowadays there is no original code left. Interface is quite similar to the jmcantrell's still. I'll mention the jmcantrells's plugin in the README, commands and functions are pretty much the same, no special comparison needed, IMHO.

**Comment by Konfekt** [comment]
Maybe a line about the motivation to fork it if the user interface is pretty much the same

**Comment by Coacher** [comment]
> Maybe a line about the motivation to fork it if the user interface is pretty much the same

It was almost 10 years ago, that context is lost. Commit history points towards missing Python3 support in jmcantrell's plugin at the time.

**Comment by Konfekt** [comment]
Oh, I thought it was rather recent. Thank you

**Comment by Coacher** [comment]
> Oh, I thought it was rather recent. Thank you

BTW, there is already a reference to jmcantrell's plugin, see `:h virtualenv-about`. No need to add it.
